### ISSUE TITLE
Nameserver management

### ISSUE THREAD

**Issue by julianmatz** [NETLINK/Blesta-UniversalDomains#3]
"If you’d like to update the nameservers for this domain name, please open a support ticket."

Is it possible to create the DNS tab, plus e-mail notification of the change and add the DNS record in the database?

http://www.blesta.com/forums/index.php?/topic/3715-domain-registration-with-universal-module/#entry42957

**Comment by wrestrtdr** [comment]
some progress?

**Comment by julianmatz** [comment]
@SIXwishlist It is done. Let me know how it works for you.

**Comment by wrestrtdr** [comment]
Hi
it works tbut the transfer of the domain does not display the options DNS and EPPCode

**Comment by julianmatz** [comment]
Try version 1.0.11-alpha.

**Comment by wrestrtdr** [comment]
Do not display the options EPP Code, transfer domain did not work just registration

**Comment by julianmatz** [comment]
Did you update the code and upgrade the module in Blesta? Make sure to also update the config file in config/universal_domains.php. If you've made changes to that file, you can use a program like WinMerge to merge the code. What TLD are you trying it with?

**Comment by wrestrtdr** [comment]
now it works but it get the mail:

```
array (
'url' => 'https://www.whoisxmlapi.com/whoisserver/WhoisService',
'args' => 
array (
'domainName' => 'werrrrrwfrj.com',
'getMode' => 'DNS_ONLY',
'outputFormat' => 'xml',
'cmd' => 'GET_DN_AVAILABILITY',
'username' => 'test',
'password' => 'test',
),
)
```

**Comment by julianmatz** [comment]
Sorry, debugging was left on. I just commited another update.

**Comment by wrestrtdr** [comment]
;)
